on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: 'Choose enviroment'
        required: true
        default: 'staging'
        type: choice
        options:
          - satging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying Application ${{ inputs.enviroment }}.."
