on: 
  repository_dispatch:
    types:
      - incident_report
jobs:
  handle-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Print indedent report
        run: echo "indedent reported"
