on: 
  workflow_dispatch:
    inputs:
      envirometn: 
        description: "Choose enviroment"
        required: true
        default: "staging"
        type: choice
        options:
          - sataging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying Application.."
        
        
