name: Scheduled test
on:
  schedule:
    - crom: '0 0 * * 0' # every Sunday at midnight
  workflow-dispatch: # allow to run manually
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Run Tests
        run: npm test
