on: 
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "i am {{ github.job }} ,and must run first"
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo "i am {{ github.job }}, i depend on job_1 cant run before he is done"
  job_3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "i am {{ github.job }}, i am parrallel dont need any other job to be done
  job_4:
    runs-on: ubuntu-latest
    needs: 
      - job_1
      - job_3
    steps:
      - run: echo "i am {{ github.job }}, i need on job_1 and job_3"
